
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: coll-website

    ports:
      - "6000:6000"

    env_file:
      - .env

    volumes:
      - .:/app
      - /app/node_modules

    restart: unless-stopped

    command: npm run dev