services:
  express-app:
    build: .
    container_name: express-website

    ports:
      - "6000:6000"

    volumes:
      - .:/app
      - /app/node_modules

    restart: unless-stopped

    command: npm run dev